version: '3'
services:
  rb_db:
    image: mysql:5.7
    container_name: rb_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=local
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=local

  rb:
    container_name: rb
    depends_on:
      - rb_db
    image: rombestilling.azurecr.io/rombestilling:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://rb_db:3306/local?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
