.frontend-test:
  image: node:12
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - frontend/**/*
        - frontend/*
      when: on_success
    - when: never
  before_script:
    - cd frontend
  cache:
    paths:
      - frontend/node_modules/

frontend-install-mr:
  extends: .frontend-test
  stage: .pre
  script:
    - yarn
  artifacts:
    paths:
      - frontend/build/
    expire_in: 15 mins

frontend-pre-mr-build:
  extends: .frontend-test
  stage: .pre
  image: andreysenov/firebase-tools:latest
  script:
    - node ./prebuild.mjs
  artifacts:
    reports:
      dotenv: build.env
    expire_in: 15 mins

frontend-lint-mr:
  extends: .frontend-test
  stage: test
  script:
    - yarn
    - yarn lint
  needs: [frontend-install-mr]

frontend-test-mr:
  extends: .frontend-test
  stage: test
  script:
    - yarn
    - yarn test
  needs: [frontend-install-mr]

frontend-build-mr:
  extends: .frontend-test
  stage: build
  script:
    - yarn
    - yarn build
  needs: [frontend-install-mr]
  artifacts:
    paths:
      - frontend/build/
    expire_in: 15 mins

frontend-deploy-mr:
  extends: .frontend-test
  stage: deploy
  image: andreysenov/firebase-tools:latest
  needs: [frontend-build-mr, frontend-pre-mr-build]
  script:
    - firebase hosting:channel:deploy $CI_COMMIT_REF_SLUG
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $MY_DEPLOYED_URL
