.backend-test:
  image: maven:3.6.3-slim
  rules:
    - if: $CI_MERGE_REQUEST_ID
      changes:
        - backend/**/*
        - backend/*
  before_script:
    - cd backend
  cache:
    paths:
      - .m2/repository
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

backend-test-mr:
  extends: .backend-test
  stage: test
  script: mvn package --activate-profiles test
  artifacts:
    when: always
    paths:
      - backend/target/site/jacoco
    reports:
      junit:
        - backend/target/surefire-reports/TEST-*.xml
