version: '3'
services:
  gidd_db:
    image: mysql:5.7
    container_name: gidd_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=local
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=local

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - gidd_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: gidd_db
      MYSQL_ROOT_PASSWORD: password