name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  check_should_skip:
    name: Check if frontend has been updated
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          cancel_others: 'false'
          paths: '["frontend/**"]'

  build:
    needs: check_should_skip
    if: ${{ needs.check_should_skip.outputs.should_skip != 'true' }}
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: frontend/build/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: frontend/build
      
      - name: Install firebase-tools
        run: npm i -g firebase-tools
        
      - name: Deploy to Firebase
        run: firebase deploy --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
