name: Deploy to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check_should_skip:
    name: Check if stun server has been updated
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          cancel_others: 'false'
          paths: '["stunserver/**", "makefile", "docker-compose.yml"]'

  build:
    needs: check_should_skip
    if: ${{ needs.check_should_skip.outputs.should_skip != 'true' }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Azure VM
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo ufw allow 3478
          cd IDATT2104-Project/stunserver
          git pull origin
          sudo make deploy < /dev/null > /tmp/mylogfile 2>&1 &
          echo "Deployment succeeded"
        host: ${{ secrets.VM_IP }}
        user: ${{ secrets.VM_USERNAME }}
        pass : ${{ secrets.VM_PASSWORD }}
        key: ""
        args: "-tt"
